#!/bin/bash
# My first script

echo "Hello bootzie!"

cd /btsync/cameras/driveway/
pwd
lftp -p 50021 -u camadmin,1friskey -e "set ftp:passive-mode false; set net:max-retries 3; mirror --verbose --Remove-source-files; rm -rf *; bye" 192.168.1.102
cd /btsync/cameras/driveway/IPCamera/FI9821W_00626E52CCD9/record
/home/hulu/./cleaner 14 100 .
