#!/bin/bash
# My first script

echo "Hello garage"

cd /btsync/cameras/garage/
pwd
lftp -p 50021 -u camadmin,1friskey -e "set ftp:passive-mode false; set net:max-retries 3; mirror --Remove-source-files ; bye" 192.168.1.104
cd /btsync/cameras/garage/IPCamera/FI9821W_C4D65539EE5E/record
/home/hulu/./cleaner 14 100 .

